[package]
name = "group_by_avg"
version = "0.1.0"
authors = ["andylokandy <andylokandy@hotmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.0"

[dev-dependencies]
criterion = "0.2"
rand = "0.7"

[[bench]]
name = "lib"
harness = false